server:
  port: 8765

management:
  security:
    enabled: false

security:
  oauth2:
    resource:
      userInfoUri: http://localhost:9999/uaa/user

zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  ignoredServices: '*'
  prefix: /api
  routes:
    product-api-service: /products/**

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO

---
# For deployment in Docker containers
spring:
  profiles: docker

server:
  port: 8765

eureka:
  instance:
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/